
### 👤 USER SERVICE
@baseUrl = http://localhost/api/users

### 1. Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "securepassword123"
}

### 2. Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "securepassword123"
}

@authToken = {{login.response.body.data.accessToken}}


### 🏦 BANKING SERVICE
@bankingUrl = http://localhost/api/banking

### 3. Deposit (Fund Wallet)
POST {{bankingUrl}}/banking/deposit
Content-Type: application/json

{
    "userId": "REPLACE_WITH_USER_ID",
    "amount": 10000,
    "narration": "Initial savings",
    "idempotencyKey": "unique-key-001"
}

### 4. Withdraw
POST {{bankingUrl}}/banking/withdraw
Content-Type: application/json

{
    "userId": "REPLACE_WITH_USER_ID",
    "amount": 2000,
    "narration": "Lunch money"
}

### 5. P2P Transfer
POST {{bankingUrl}}/banking/transfer
Content-Type: application/json

{
    "senderUserId": "SENDER_ID",
    "receiverUserId": "RECEIVER_ID",
    "amount": 500,
    "narration": "Gift for friend"
}

### 6. Transaction History
GET {{bankingUrl}}/banking/transactions/history/REPLACE_WITH_USER_ID?page=1&limit=10

### 7. Get Transaction by Ref
GET {{bankingUrl}}/banking/transactions/ref/TXN-FUND-123456789
