services:
  users-db:
    image: postgres:15-alpine
    container_name: users-db
    restart: always
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_service_db
    ports:
      - "5431:5432"
    expose:
      - "5431"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data

  banking-db:
    image: postgres:15-alpine
    container_name: banking-db
    restart: always
    environment:
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core_banking_service_db
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - banking_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: wallet-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  nginx:
    image: nginx:alpine
    container_name: wallet-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user-service
      - core-banking

  user-service:
    build:
      context: ./apps/user-service
      dockerfile: dockerfile
    container_name: user-service
    restart: on-failure
    command: sh -c "npm ci --force && npm run dev --force"
    expose:
      - "3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://users:password@users-db:5432/users_service_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
      - JWT_SECRET=supersecret
      - LOG_LEVEL=debug
    depends_on:
      - users-db
      - rabbitmq
    volumes:
      - ./apps/user-service:/app
      - /app/node_modules

  core-banking:
    build:
      context: ./apps/core-banking
      dockerfile: dockerfile
    container_name: core-banking
    restart: on-failure
    command: sh -c "npm ci --force && npm run dev --force"
    expose:
      - "3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://banking:password@banking-db:5432/core_banking_service_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    depends_on:
      - banking-db
      - rabbitmq
    volumes:
      - ./apps/core-banking:/app
      - /app/node_modules

volumes:
  users_postgres_data:
  banking_postgres_data:
  user_node_modules:
  banking_node_modules:
